### ISSUE TITLE
[enhanced] Sugestoes de melhoria

### ISSUE THREAD

**Issue by lue93** [betha-plataforma/plataforma-integracao#1]
Ola time betha. 

Eu estava navegando no linkedin e encontrei voces, e vi esse repositorio. 
Acabei navegando pelo codigo do backend, e gostaria de fazer alguns comentarios, claro se for do agrado de voces. :) , considerando ser codigo aberto e que sera usado por clientes.

1. Adicionar ao gitignore a pasta target e demais defaults
https://stackoverflow.com/questions/991801/git-ignores-and-maven-targets
(Mesmo deletando as chaves de acesso, as mesmas permanecem no bytecode da pasta target, suponho que as mesmas ja foram inutilizadas, provavelmente seria melhor deletar esse repositorio, e criar outro sem esse historico de chaves)
Bytecode compilado contendo chaves de acesso
https://github.com/betha-plataforma/plataforma-integracao/blob/6c90dfae1fc808fe42bb0bd50c8a7913f27fbfd3/back/target/classes/config/application-local.yaml#L13

2. Testes unitarios com mocks aos endpoints
2.1 Aqui seria interessante tbm criar mocks para quem for parceiro, e por ventura efetuar testes.

3. Suporte ao swagger como documentacao.

4. O codigo possui duas linguas ingles e portugues, nao seria interessamente manter apenas uma ? 

5. Vi que existe interfaces implementadas que executam comandos, nao seria legal seguir o pattern command handler e abstrair a camada de dados em relacao a de execucao ? 
5.1 Alem disso, a cadastro unico nao poderia ser uma classe concreta que segue o contrato mais generico ?

Obrigado pela atencao, e desculpem o incomodo.

**Comment by guilhermeclamego** [comment]
Olá, boa tarde!

Agradecemos pelo feedback, são itens com bastante relevância para este projeto.
Ele ainda está em fase bem inicial, foi feito para uma apresentação, mas já temos mapeados algumas melhorias e refatorações para eles.
Além das citadas por você, também queremos adicionar uma camada do Spring Security, tendo autenticação com JWT, adicionar Spring Actuator juntamente com o Spring Boot Admin. 

Mais uma vez, obrigado pela contribuição, em breve iremos subir essas features. 

Abraço!
